/**
 * lsp init-backlog — Convert .lsp/tasks.md to specs/backlog.md in AutoSpec Sprint 1 format
 */

import { Command } from 'commander';
import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Walk up from startDir until a .lsp/ directory is found.
 * Returns the full path to .lsp/ or null if not found.
 */
function findLspDir(startDir: string): string | null {
  let dir = startDir;
  while (true) {
    const candidate = path.join(dir, '.lsp');
    if (fs.existsSync(candidate)) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/**
 * Map a time estimate string to story points and model selection.
 *
 * | Est. Time | Points | Model  |
 * |-----------|--------|--------|
 * | 30m       | 1      | haiku  |
 * | 1h        | 2      | haiku  |
 * | 2h        | 3      | sonnet |
 * | 4h        | 5      | sonnet |
 * | 8h        | 8      | sonnet |
 * | anything else | 3  | sonnet |
 */
export function timeToPoints(timeStr: string): { points: number; model: string } {
  const t = (timeStr ?? '').trim().toLowerCase();
  if (t.includes('30m')) return { points: 1, model: 'haiku' };
  if (t === '1h' || t === '1 h') return { points: 2, model: 'haiku' };
  if (t === '2h' || t === '2 h') return { points: 3, model: 'sonnet' };
  if (t === '4h' || t === '4 h') return { points: 5, model: 'sonnet' };
  if (t === '8h' || t === '8 h') return { points: 8, model: 'sonnet' };
  return { points: 3, model: 'sonnet' };
}

interface ParsedTask {
  id: string;
  task: string;
  points: number;
  model: string;
}

/**
 * Parse task table rows from tasks.md content.
 *
 * tasks.md format (produced by formatTasksMarkdown in task-extractor.ts):
 *   | # | Task | Priority | Estimate | Status |
 *   |---|------|----------|----------|--------|
 *   | 1 | Set up project structure | High | 30m | [ ] |
 *   | 2 | Implement CSV parser | Medium | 2h | [ ] |
 */
export function parseTasksMarkdown(content: string): ParsedTask[] {
  const tasks: ParsedTask[] = [];
  const lines = content.split('\n');

  for (const line of lines) {
    // Match table rows that start with a numeric ID: | 1 | ... |
    const match = line.match(/^\|\s*(\d+)\s*\|(.+)$/);
    if (!match) continue;

    const cols = line
      .split('|')
      .map(c => c.trim())
      .filter(Boolean);

    // cols[0] = id, cols[1] = task, cols[2] = priority, cols[3] = estimate, cols[4] = status
    const idNum = parseInt(cols[0] ?? '', 10);
    if (isNaN(idNum)) continue;

    const taskTitle = cols[1] ?? '';
    const estimateStr = cols[3] ?? '';

    // Skip header row ("Task" column) and separator rows ("---")
    if (taskTitle.toLowerCase() === 'task' || taskTitle.includes('---')) continue;
    if (!taskTitle) continue;

    const { points, model } = timeToPoints(estimateStr);
    tasks.push({ id: String(idNum), task: taskTitle, points, model });
  }

  return tasks;
}

/**
 * Generate specs/backlog.md content in AutoSpec Sprint 1 format.
 */
export function generateBacklogMarkdown(
  projectName: string,
  tasks: ParsedTask[],
  today: string,
): string {
  const totalPts = tasks.reduce((s, r) => s + r.points, 0);

  const tableRows = tasks
    .map(r => `| 1.${r.id} | ${r.task} | Fullstack | ${r.model} | ${r.points} | 🔲 | — |`)
    .join('\n');

  return [
    `# ${projectName} — SDD Project Backlog`,
    '',
    '**Version:** 1.0',
    `**Created:** ${today}`,
    '**Generated by:** `lsp init-backlog` from .lsp/tasks.md',
    '',
    '---',
    '',
    `## Sprint 1: Initial Implementation (~${totalPts} pts)`,
    '',
    '**Theme:** Implement core features from LightSpec spec',
    '**Status:** 🔲 Planned',
    '',
    '| ID | Ticket | Owner | Model | Points | Status | Deps |',
    '|----|--------|-------|-------|--------|--------|------|',
    tableRows,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Command factory
// ---------------------------------------------------------------------------

export function makeInitBacklogCommand(): Command {
  const cmd = new Command('init-backlog');
  cmd
    .description('Convert .lsp/tasks.md to specs/backlog.md in AutoSpec format')
    .option('--dir <path>', 'Path to project directory')
    .option('--yes', 'Overwrite existing backlog without prompting')
    .action(async (opts: { dir?: string; yes?: boolean }) => {
      // 1. Resolve project directory
      const projectDir = opts.dir ? path.resolve(opts.dir) : process.cwd();

      // 2. Find tasks.md — search upward if not in projectDir directly
      let tasksPath: string;
      const directLsp = path.join(projectDir, '.lsp', 'tasks.md');
      if (fs.existsSync(directLsp)) {
        tasksPath = directLsp;
      } else {
        const foundLsp = findLspDir(projectDir);
        if (!foundLsp || !fs.existsSync(path.join(foundLsp, 'tasks.md'))) {
          console.error(chalk.red('No .lsp/tasks.md found. Run `lsp init` first.'));
          process.exit(1);
        }
        tasksPath = path.join(foundLsp, 'tasks.md');
      }

      // 3. Check for existing backlog.md
      const specsDir = path.join(projectDir, 'specs');
      const backlogPath = path.join(specsDir, 'backlog.md');

      if (fs.existsSync(backlogPath) && !opts.yes) {
        console.log(chalk.yellow('specs/backlog.md already exists. Use --yes to overwrite.'));
        process.exit(0);
      }

      // 4. Parse tasks.md
      const content = await fs.readFile(tasksPath, 'utf-8');
      const tasks = parseTasksMarkdown(content);

      if (tasks.length === 0) {
        console.error(chalk.red('No tasks found in .lsp/tasks.md. Run `lsp init` to generate tasks.'));
        process.exit(1);
      }

      // 5. Generate backlog.md
      const projectName = path.basename(projectDir);
      const today = new Date().toISOString().slice(0, 10);
      const backlog = generateBacklogMarkdown(projectName, tasks, today);

      // 6. Write output
      await fs.ensureDir(specsDir);
      await fs.writeFile(backlogPath, backlog, 'utf-8');

      const totalPts = tasks.reduce((s, r) => s + r.points, 0);
      console.log(
        chalk.green(`✓ Created specs/backlog.md (${tasks.length} tickets, ${totalPts} pts)`),
      );
      console.log(chalk.dim('  Ready to use with /execute-ticket in Claude Code'));
    });

  return cmd;
}
